spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xs
    username: root
    password: zzjlq123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  mail:
    host: smtp.qq.com
    username: 837447352@qq.com
    password: qxznuvmhfcxhbgac
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true